<?php

namespace App\Http\Livewire;

use Livewire\Component;
use App\Services\OpenAIService;

class PropertyForm extends Component
{
    public $title;
    public $propertyType;
    public $location;
    public $price;
    public $keyFeatures;
    public $description;
    public $tone = 'Formal';
    public $seoScore = null;

    protected $rules = [
        'title' => 'required|string|max:255',
        'propertyType' => 'required|string',
        'location' => 'required|string|max:255',
        'price' => 'required|numeric|min:0',
        'keyFeatures' => 'nullable|string',
        'tone' => 'nullable|string',
    ];

    public function generateDescription()
    {
        $this->validate();

        // Call AI service to generate a description. If no API key is configured,
        // the service will return a deterministic, helpful fallback.
        $ai = app(OpenAIService::class);
        $this->description = $ai->generateDescription([
            'title' => $this->title,
            'property_type' => $this->propertyType,
            'location' => $this->location,
            'price' => $this->price,
            'key_features' => $this->keyFeatures,
            'tone' => $this->tone,
        ]);

        $this->seoScore = $this->calculateSeoScore($this->description);
    }

    public function regenerateDescription()
    {
        $ai = app(OpenAIService::class);
        $this->description = $ai->generateDescription([
            'title' => $this->title,
            'property_type' => $this->propertyType,
            'location' => $this->location,
            'price' => $this->price,
            'key_features' => $this->keyFeatures,
            'tone' => $this->tone,
        ], ['alternate' => true]);

        $this->seoScore = $this->calculateSeoScore($this->description);
    }

    private function createDescription()
    {
     // Keep backward compatible fallback (not used now) — generated by service instead.
     return "Discover this {$this->propertyType} located in {$this->location}. " .
         "This property features: {$this->keyFeatures}. " .
         "Available for just {$this->price}.";
    }

    public function render()
    {
        // Render the Livewire-specific component view to avoid recursive mounting
        return view('livewire.property-form');
    }

    private function calculateSeoScore(?string $text): int
    {
        if (empty($text)) {
            return 0;
        }

        $score = 0;

        // length: 2-4 short paragraphs desirable -> 80-200 words
        $wordCount = str_word_count(strip_tags($text));
        if ($wordCount >= 80 && $wordCount <= 220) {
            $score += 40;
        } elseif ($wordCount >= 50 && $wordCount < 80) {
            $score += 20;
        }

        // presence of location and at least one key feature
        if (!empty($this->location) && str_contains(strtolower($text), strtolower($this->location))) {
            $score += 30;
        }

        if (!empty($this->keyFeatures)) {
            $features = explode(',', $this->keyFeatures);
            foreach ($features as $f) {
                if (str_contains(strtolower($text), strtolower(trim($f)))) {
                    $score += 10;
                    break;
                }
            }
        }

        // tone variety: prefer not to be too repetitive
        if (!empty($this->tone)) {
            $score += 10;
        }

        return min(100, (int) $score);
    }
}